# Numpy
 
### Learning Numpy from all sources available

In [51]:
import numpy as np

In [2]:
# creating a nus a limpy arraycti
# NOTE, numpy is a list of list or dictonary of list

a = np.array([1, 2, 3, 4])
print(a)

b = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
b

[1 2 3 4]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# Get "DIMENSION"

print(b.ndim)

a.ndim

2


1

In [5]:
# Get "SHAPE"

b.shape

(2, 4)

In [16]:
# Get "itemsize"

print(a.itemsize)

b.itemsize

4


4

In [17]:
# Get "size"

print(a.size)

b.size

4


8

In [20]:
array_test = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(array_test)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
# index Slicing (start:end:step)
# array_test[row_start:row_end:row_step, column_start:column_end:column_step]

array_test[1:, 0:2]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [4]:
# Get "TOTALSIZE"

b.nbytes

32

In [44]:
# Hash Analytics TEST

array_a = np.arange(0,100,5).reshape(4,5)

print(array_a)
print()
print(array_a[0:2, -1:1:-1])
print()
print(array_a[1:3])

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]

[[20 15 10]
 [45 40 35]]

[[25 30 35 40 45]
 [50 55 60 65 70]]


In [67]:
# Numpy Math

a = np.arange(1,20,2)
b = np.arange(2,21,2)

print(np.sum(a))
print(np.cumsum(a))
print(np.prod(a))
print(np.cumprod(a))
print(np.mean(a))
print(np.std(a))
print(np.var(a))
# Vector product of 2 arrays
print("Vector product of 2 arrays: ", np.dot(a, b))

100
[  1   4   9  16  25  36  49  64  81 100]
654729075
[        1         3        15       105       945     10395    135135
   2027025  34459425 654729075]
10.0
5.74456264654
33.0
Vector product of 2 arrays:  1430


In [75]:
# Same as above

print(b.sum())
print(b.cumsum())
print(b.cumsum()[-1]) #trying to get only the last number
print(b.prod())
print(b.cumprod())
print('min_value: ', b.min())
print('max_value: ', b.max())
# print('idx: ', b.idxmax())
print('ptp(max_value - min_value): ', b.ptp()) # max_value - min_value
print('mean_value: ', b.mean())
print('standard_variance: ', b.std())
print('variance: ', b.var())
print()
print("power(base^exp i.e (a^b)): ", np.power(a, b)) # a=base, b=exp. pover is base^exp (a^b)

110
[  2   6  12  20  30  42  56  72  90 110]
110
-579076096
[         2          8         48        384       3840      46080
     645120   10321920  185794560 -579076096]
min_value:  2
max_value:  20
ptp(max_value - min_value):  18
mean_value:  11.0
standard_variance:  5.74456264654
variance:  33.0

power(base^exp i.e (a^b)):  [          1          81       15625     5764801 -2147483648 -2147483648
 -2147483648 -2147483648 -2147483648 -2147483648]


C:\Users\USER\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\__main__.py:16: RuntimeWarning: invalid value encountered in power


In [63]:
# BROADCAST

np1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
np2 = np.array([3,5,7])
np3 = np.array([[1], [2], [3]])
print(np1 * np2)
print()
print(np1 * np3)

[[ 3 10 21]
 [12 25 42]
 [21 40 63]]

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [41]:
# use "where" : np.where(condition, true_value, false_value)

where_bol = np.where(a>10)
print(where_bol)
print()
where = np.where(a>10, a, 0)
print(where)

(array([5, 6, 7, 8, 9], dtype=int64),)

[ 0  0  0  0  0 11 13 15 17 19]


In [43]:
# use "Any" & "ALL"
condition = np.array([True, False, True, True])
print(condition.any()) # or operator
print(condition.all()) #and operator

True
False


In [50]:
# use "unique" (datas/values that are unique in an array) & "nunique" (number of unique values)

unique_exp = np.array(['solid', 'solid', 'solid', 'liquid', 'liquid', 'liquid', 'gas', 'gas'])
print(np.unique(unique_exp))
#np.nunique(unique_exp) # this can be found in  pandas


in_1d = np.in1d(['solid', 'gas', 'platinum'],unique_exp)
print(in_1d)

['gas' 'liquid' 'solid']
[ True  True False]


In [29]:
# "LOGSPACE"

npy_logspace = np.logspace(2, 6, 10 )

npy_logspace

# output return 10^2 - 10^6

array([  1.00000000e+02,   2.78255940e+02,   7.74263683e+02,
         2.15443469e+03,   5.99484250e+03,   1.66810054e+04,
         4.64158883e+04,   1.29154967e+05,   3.59381366e+05,
         1.00000000e+06])

In [32]:
#changing data type can be done in two ways

print(npy_logspace.astype(int))
print("or") 
print(np.logspace(2, 6, 10, dtype=int))

[    100     278     774    2154    5994   16681   46415  129154  359381
 1000000]
or
[    100     278     774    2154    5994   16681   46415  129154  359381
 1000000]


In [33]:
# "ZEROS"

np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [34]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [35]:
np.zeros((2,3,3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [8]:
np.zeros((4,2,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [9]:
# "ONES" : this thesame way as zeros 
# np.ones((4,2,3,3)) ie np.ones((no of matrix2 for matrix1,no of matrix1 for r&c, row, column))

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
# "diagonal"

np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [11]:
# "IDENTITY"

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# same as code above
  
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# "FULL" np.full((no row,no column), no of item to full the matrix)

np.full((3,3), 22)

array([[22, 22, 22],
       [22, 22, 22],
       [22, 22, 22]])

In [54]:
# this is to show you can have a infinity amount of loop

np.full((3,2,3,3), 22, dtype='int32')

array([[[[22, 22, 22],
         [22, 22, 22],
         [22, 22, 22]],

        [[22, 22, 22],
         [22, 22, 22],
         [22, 22, 22]]],


       [[[22, 22, 22],
         [22, 22, 22],
         [22, 22, 22]],

        [[22, 22, 22],
         [22, 22, 22],
         [22, 22, 22]]],


       [[[22, 22, 22],
         [22, 22, 22],
         [22, 22, 22]],

        [[22, 22, 22],
         [22, 22, 22],
         [22, 22, 22]]]])

In [56]:
# linspace(start, end, number of seperation times)

np.linspace(1, 10, 10)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [16]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [58]:
# numpy.arage (start, end, step)

# Example 1
arange = np.arange(10)
print("arange: ", arange)

#same as

numpy_range = np.array(range(10))
print("\nnumpy_range: ", numpy_range)

# Example 2
# using step count
np.arange(0, 20+1, 2)

arange:  [0 1 2 3 4 5 6 7 8 9]

numpy_range:  [0 1 2 3 4 5 6 7 8 9]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

NameError: name 'xange' is not defined

In [14]:
# converting int, float and even boolen to (boolen) using "astype()"

test = np.array([0, 2.5, 3, 3, True, 0.01, 0.0]).dtype(bool)

test

TypeError: 'numpy.dtype' object is not callable

In [19]:
# converting boolen, int, float to (int or float) using "astype()"

numpy_boolen =np.array([True, False, False, True, 1, 1.0])

print(numpy_boolen.astype(float))
print(numpy_boolen.astype(int))

[1. 0. 0. 1. 1. 1.]
[1 0 0 1 1 1]


In [20]:
# "REPEAT" as it name implies

# this will repeat the amount of row using "AXiS=0"
arr = np.array([[1,2,3,4,5]])
rep1 = np.repeat(arr,3, axis=0)
print(rep1)
print("\n")

# this will repeat the amount of column using "AXiS=1"
rep2 = np.repeat(arr,3, axis=1)
print(rep2)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


[[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]]


### Numple RANDOM Sampling 

##### i.   rand
##### ii.  randn
##### iii. randf
##### iv.  randint

In [3]:
# "random.RANDOM" basically random floating values btw "0 - 1" that is  0 inclusive and 1 exclusive

np.random.random()

0.7929299350139033

In [6]:
np.random.random(3)

array([0.59235185, 0.37570167, 0.46687264])

In [11]:
np.random.random((3,2))

array([[[0.37821738, 0.51807571],
        [0.35017664, 0.12095247],
        [0.769808  , 0.42653505]],

       [[0.12351398, 0.46369399],
        [0.73216802, 0.55214313],
        [0.8427644 , 0.43663975]]])

In [42]:
# "random.UNIFORM" uniform(low=0.0, high=1.0, size=None), 
# returns a float value that is "lower value" inclusive and "highest value" exclusive

np.random.uniform()

0.1246638774271539

In [62]:
np.random.uniform(1,7)

4.656300022548863

In [63]:
np.random.uniform(1,5,5)

array([1.90871348, 3.8216123 , 3.44460378, 1.6793382 , 2.5384976 ])

In [123]:
# "random_sample(size=None)" 
# return output of 0.0 - 1.0 with 1.0 exclus!ve i.e 0.1-0.99 
# returns a float, of NO negat!ve value

sample = np.random.sample()
print(sample, "\n")

sample_size = np.random.sample((3,4))
print(sample_size, "\n")

#this code below gives an error

# (  array = np.arange(5)
# print(array, "\n")

# sample_array = np.random.sample(array, (3,))
# print(sample_array, "\n")                    )

0.9308617522870657 

[[0.38600175 0.4952853  0.61916998 0.25802534]
 [0.79297876 0.27252666 0.64729525 0.29434915]
 [0.94457466 0.00326188 0.92023331 0.39556686]] 



In [112]:
np.random.rand()

0.933480927426284

In [13]:
np.random.rand(3)

array([0.44531246, 0.34824351, 0.00219764])

In [68]:
np.random.rand(3,2)

array([[0.15830987, 0.87993703],
       [0.27408646, 0.41423502],
       [0.29607993, 0.62878791]])

In [69]:
np.random.rand(2,3,2)

array([[[0.57983781, 0.5999292 ],
        [0.26581912, 0.28468588],
        [0.25358821, 0.32756395]],

       [[0.1441643 , 0.16561286],
        [0.96393053, 0.96022672],
        [0.18841466, 0.02430656]]])

In [71]:
np.random.randn?

In [83]:
np.random.randn()

0.6448475108927784

In [82]:
np.random.randn(3)

array([ 1.15139101,  1.85733101, -1.51117956])

In [86]:
np.random.randn(3,4)

array([[-0.10716398,  2.26010677,  0.65661947,  0.12480683],
       [-0.43570392,  0.97217931, -0.24071114, -0.82412345],
       [ 0.56813272,  0.01275832,  1.18906073, -0.07359332]])

In [81]:
# "randint" randint(low, high=None, size=None, dtype='l')
# must have atleast one argument
# "low value" inclusive and "high value" exclusive
# returns an int 

np.random.randint(4)

2

In [87]:
np.random.randint(4, size=(10))

array([1, 2, 2, 2, 1, 1, 0, 1, 2, 0])

In [86]:
np.random.randint(4,10, size=(2,3))

array([[5, 6, 8],
       [9, 9, 9]])

In [89]:
np.random.randint(2,9, size=(2,3,2,3))

array([[[[7, 3, 3],
         [5, 2, 2]],

        [[8, 2, 3],
         [4, 3, 8]],

        [[6, 2, 4],
         [2, 4, 7]]],


       [[[7, 6, 7],
         [4, 3, 5]],

        [[3, 7, 2],
         [5, 8, 2]],

        [[4, 3, 2],
         [2, 3, 4]]]])

In [22]:
npy_rand = np.random.randint(-1, 10, size=(4,3))
npy_rand

array([[ 2,  5,  5],
       [-1,  8,  7],
       [ 3,  6, -1],
       [-1,  6,  0]])

In [23]:
npy_rand.shape

(4, 3)

In [76]:
# i still dont know what this code does , ie using random.seed

seed = np.random.seed(5)
seed

In [91]:
# "choice" choice(a, size=None, replace=True, p=None)
# size is int or tuple
# p is probability

name_list = ["damsel", "olamide", "abiodun", "essy", "samuel"]
np.random.choice(name_list)

'samuel'

In [92]:
np.random.choice(name_list, 3)

array(['abiodun', 'samuel', 'essy'], dtype='<U7')

In [94]:
np.random.choice(name_list, (2,3,2), p=[.5, .1, .3, .1, 0 ])

array([[['damsel', 'essy'],
        ['abiodun', 'damsel'],
        ['essy', 'damsel']],

       [['abiodun', 'abiodun'],
        ['damsel', 'damsel'],
        ['abiodun', 'damsel']]], dtype='<U7')

In [107]:
# "shuffle": shuffle(x)
# takes only one argument
# as its name implies, it returns a shuffled array

# "arange" returns array of of range as!n list(range(10))
arr = np.arange(10)
print(arr, "\n")

# "shuffle" shuffles arr
np.random.shuffle(arr)
print(arr, "\n")

# "reshape" helps to shape an array temporar!ly, excepy expl!ctly called
arr = np.arange(12).reshape(4,3)
np.random.shuffle(arr)
arr


[0 1 2 3 4 5 6 7 8 9] 

[2 1 5 7 4 6 0 8 9 3] 



array([[ 6,  7,  8],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [102]:
np.random.shuffle?

In [24]:
# "SHAPE" will help convert the shape to the new shape assiged

npy_rand.shape = (12, 1 )

print(npy_rand)

npy_rand.shape = (12, )
print("\n", npy_rand)

[[ 2]
 [ 5]
 [ 5]
 [-1]
 [ 8]
 [ 7]
 [ 3]
 [ 6]
 [-1]
 [-1]
 [ 6]
 [ 0]]

 [ 2  5  5 -1  8  7  3  6 -1 -1  6  0]


In [25]:
# "RESHAPE" this change the of the shape "temporarily" to the new shape called 
# ... without changing its original variable shape in location

npy_rand.reshape(2, 6)

array([[ 2,  5,  5, -1,  8,  7],
       [ 3,  6, -1, -1,  6,  0]])

In [26]:
npy_rand.reshape(2, 6).shape

(2, 6)

In [27]:
# using "TRANSPOSE" convert rows to column and columns to row

npy_rand.transpose()

array([ 2,  5,  5, -1,  8,  7,  3,  6, -1, -1,  6,  0])

In [28]:
transpose_shape = npy_rand.transpose().shape
transpose_shape

(12,)

In [29]:
# using "RAVEL" unravels the array into a one dimensional array 

npy_rand.ravel()

array([ 2,  5,  5, -1,  8,  7,  3,  6, -1, -1,  6,  0])

In [30]:
npy_rand.ravel().shape

(12,)

### Mathematical computations

In [50]:
# from a
print(a)

[1 2 3 4]


In [51]:
a += 2
a

array([3, 4, 5, 6])

In [52]:
plus = a + 2
minus = a - 2
mult = a * 2
divide = (a / 2).astype(int)
modulus = a % 2

print(plus, "\n", minus, "\n", mult, "\n", divide, "\n", modulus)

[5 6 7 8] 
 [1 2 3 4] 
 [ 6  8 10 12] 
 [1 2 2 3] 
 [1 0 1 0]


In [55]:
# from b above
print(a)
print("\n")
print(b)
a + b

[3 4 5 6]


[[1 2 3 4]
 [5 6 7 8]]


array([[ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [47]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [56]:
np.cos(b)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003]])

In [58]:
np.sinh(a)

array([ 10.01787493,  27.2899172 ,  74.20321058, 201.71315737])

In [60]:
np.arctan(a)

array([1.24904577, 1.32581766, 1.37340077, 1.40564765])

In [61]:
np.degrees(a)

array([171.88733854, 229.18311805, 286.47889757, 343.77467708])

In [62]:
np.radians(b) 

array([[0.01745329, 0.03490659, 0.05235988, 0.06981317],
       [0.08726646, 0.10471976, 0.12217305, 0.13962634]])

check here for more

[numpy_mathematical_documentation]https://docs.scipy.org/doc/numpy/reference/routines.math.html

linear Algberal

In [58]:
# "MATMUL()", 

# Example 1
x = np.ones((3,2))
print(x)

y = np.full((2,3), 2)
print("\n", y)

np.matmul(x,y)

# %except_exception x*y
# this code will not work, because 2 columns cant mult 3 colums

[[1. 1.]
 [1. 1.]
 [1. 1.]]

 [[2 2 2]
 [2 2 2]]


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [60]:
# Example 2

x = np.ones((7,4))
print(x)

y = np.full((4,7), 2)
print("\n", y)

np.matmul(x,y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]


array([[8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8.]])

In [61]:
np.sum(x,y)

TypeError: only integer scalar arrays can be converted to a scalar index