# PANDAS

In [1]:
import pandas as pd
import numpy as np


### NUMPY: Axis=1 means across "row",   Axis=0 means across "column"

### PANDAS : Axis=1 is COLUMN while Axis=0 is Row

In [76]:
# NUMPY

axis_0_1_test = np.array([[1,2,3,4], [5,6,7,8]])
print(axis_0_1_test)
print()
print('axis_1 (across the rows): ', axis_0_1_test.sum(axis=1))
print('axis_0 (across the columns): ', axis_0_1_test.sum(axis=0))


[[1 2 3 4]
 [5 6 7 8]]

axis_1 (across the rows):  [10 26]
axis_0 (across the columns):  [ 6  8 10 12]


[[ 3 10 21]
 [12 25 42]
 [21 40 63]]

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


In [4]:
np.array([3] *4) *2

array([6, 6, 6, 6])

In [ ]:
# THIS DID NOT WORK

# df = pd.read_csv('data/Pandas Data Science Tutorial.ipynb.txt')
# df

## Series

In [69]:
# using Time Series Data within Series

date_1 = pd.date_range("20120204", periods=4)
date_2 = pd.date_range('2/4/2020', periods=4)

series_exp = pd.Series(np.array(['a','b','c','d']), index=date)
series_exp


2012-02-04    a
2012-02-05    b
2012-02-06    c
2012-02-07    d
Freq: D, dtype: object

In [40]:
index_2 = ['index1', 'index2', 'index3', 'index4']
np_array = np.arange(2,10,2)

series_exp_2 = pd.Series(np_array, index_2)
print(series_exp_2.values)
print(series_exp_2.index)


#naming the index
series_exp_2.index.name = 'index_name'

# naming the series data
series_exp_2.name = 'Series'
series_exp_2

[2 4 6 8]
Index(['index1', 'index2', 'index3', 'index4'], dtype='object')


index_name
index1    2
index2    4
index3    6
index4    8
Name: Series, dtype: int32

###  Isnull() & notnull()

In [41]:
# finding out is there 'is a null value' within the pandas data

series_exp_2.isnull()


index_name
index1    False
index2    False
index3    False
index4    False
Name: Series, dtype: bool

In [42]:
# finding out is there 'isn't a null value' within the pandas data

series_exp_2.notnull()

index_name
index1    True
index2    True
index3    True
index4    True
Name: Series, dtype: bool

## DataFrame

In [ ]:
# trying to read data from clipboard did not work

# clipboard_df = pd.read_html(https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue#List_of_largest_companies_by_revenue, )
# clipboard_df

###  Read_CSV()

In [84]:

df = pd.read_csv('data/pokemon_data.txt', delimiter='\t', index_col='#')
df.head()

Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
#                                                                       
1              Bulbasaur  Grass  Poison  45      49       49       65   
2                Ivysaur  Grass  Poison  60      62       63       80   
3               Venusaur  Grass  Poison  80      82       83      100   
3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation Legendary  
#                                        
1       65     45           1     False  
2       80     60           1     False  
3      100     80           1     False  
3      120     80           1     False  
4       50     65           1     False

In [92]:
df.so

AttributeError: 'Series' object has no attribute 'value'

### Working with 'Columns'

In [ ]:
# Pulling out Columns

# print(df.columns)
# print()
# print(df['Name'][0:10])
# print()
# print(df[['Name', 'HP', 'Defense']].head(10))


### Adding New Column


In [70]:
df['Range'] = np.arange(0,(len(df)*2),2)

df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Speed'] + df['Sp. Def'] + df['Sp. Atk']
# same as
#df['Total_index'] = df.iloc[:, 4:10].sum(axis=1)

df.head(10)


Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
#                                                                           
1                  Bulbasaur  Grass  Poison  45      49       49       65   
2                    Ivysaur  Grass  Poison  60      62       63       80   
3                   Venusaur  Grass  Poison  80      82       83      100   
3      VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4                 Charmander   Fire     NaN  39      52       43       60   
5                 Charmeleon   Fire     NaN  58      64       58       80   
6                  Charizard   Fire  Flying  78      84       78      109   
6  CharizardMega Charizard X   Fire  Dragon  78     130      111      130   
6  CharizardMega Charizard Y   Fire  Flying  78     104       78      159   
7                   Squirtle  Water     NaN  44      48       65       50   

   Sp. Def  Speed  Generation Legendary  Range  Total  
#                                                      
1       65     45           1     False      0    318  
2       80     60           1     False      2    405  
3      100     80           1     False      4    525  
3      120     80           1     False      6    625  
4       50     65           1     False      8    309  
5       65     80           1     False     10    405  
6       85    100           1     False     12    534  
6       85    100           1     False     14    634  
6      115    100           1     False     16    634  
7       64     43           1     False     18    314

###  Delecting a Column permanent with inplace=True

In [75]:
df.drop("Range", inplace=True)
df.head()

Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
#                                                                       
1              Bulbasaur  Grass  Poison  45      49       49       65   
2                Ivysaur  Grass  Poison  60      62       63       80   
3               Venusaur  Grass  Poison  80      82       83      100   
3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation Legendary  Total  
#                                               
1       65     45           1     False    318  
2       80     60           1     False    405  
3      100     80           1     False    525  
3      120     80           1     False    625  
4       50     65           1     False    309

### Working with 'Rows'

use 'loc' selecting by `index_name`, use 'iloc' selcting by `index_number`.


Also see 'at' & 'iat'

In [11]:
# pulling out "rows"

df[0:5]
# or 
df.loc[0:5]

# print(df.iloc[1])
# # same as 
# print('\n SAME AS \n')
# print(df.loc[1])


Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
#                                                                       
1              Bulbasaur  Grass  Poison  45      49       49       65   
2                Ivysaur  Grass  Poison  60      62       63       80   
3               Venusaur  Grass  Poison  80      82       83      100   
3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4             Charmander   Fire     NaN  39      52       43       60   
5             Charmeleon   Fire     NaN  58      64       58       80   

   Sp. Def  Speed  Generation Legendary  
#                                        
1       65     45           1     False  
2       80     60           1     False  
3      100     80           1     False  
3      120     80           1     False  
4       50     65           1     False  
5       65     80           1     False

### Accessing Rows and Columns

Selecting specific [rows, columns] using 'loc', 'iloc', 'at', & 'iat'

In [24]:
df.iloc[0:5, 3:10]
# same as
# df.loc[0:5, 'HP':'Speed']

# df.loc[5, 'Type 1':'Type 2']

# df.loc[:, 'Name':'Type 2' ]
# same as
# df.iloc[:, 0:3]


#using loc.iloc, at, iat
df.loc[2, 'Legendary']
# same as
df.iloc[2, 10]
# same as
df.at[2, 'Legendary']
#same as
df.iat[2, 10]

False

### Describe

In [ ]:
df_describe = df.describe()
df_describe

In [ ]:
df_describe.loc['mean':'std']

# same as
# df_describe.iloc[1:3]

### Data Filtering

In [25]:
df[df['Legendary'] == True].head()

Name    Type 1    Type 2   HP  Attack  Defense  Sp. Atk  \
#                                                                             
144             Articuno       Ice    Flying   90      85      100       95   
145               Zapdos  Electric    Flying   90      90       85      125   
146              Moltres      Fire    Flying   90     100       90      125   
150               Mewtwo   Psychic       NaN  106     110       90      154   
150  MewtwoMega Mewtwo X   Psychic  Fighting  106     190      100      154   

     Sp. Def  Speed  Generation Legendary  
#                                          
144      125     85           1      True  
145       90    100           1      True  
146       85     90           1      True  
150       90    130           1      True  
150      100    130           1      True

In [26]:
filtered = df[(df['Type 1'] == 'Ice') | (df['Type 2'] == 'Dragon') & (df['HP'] > 100)]
filtered.head(10)

Name Type 1   Type 2   HP  Attack  Defense  Sp. Atk  \
#                                                                       
124               Jynx    Ice  Psychic   65      50       35      115   
144           Articuno    Ice   Flying   90      85      100       95   
220             Swinub    Ice   Ground   50      50       40       30   
221          Piloswine    Ice   Ground  100     100       80       60   
225           Delibird    Ice   Flying   45      55       45       65   
238           Smoochum    Ice  Psychic   45      30       15       85   
361            Snorunt    Ice      NaN   50      50       50       50   
362             Glalie    Ice      NaN   80      80       80       80   
362  GlalieMega Glalie    Ice      NaN   80     120       80      120   
363             Spheal    Ice    Water   70      40       50       55   

     Sp. Def  Speed  Generation Legendary  
#                                          
124       95     95           1     False  
144      125     85           1      True  
220       30     50           2     False  
221       60     50           2     False  
225       45     75           2     False  
238       65     65           2     False  
361       50     50           3     False  
362       80     80           3     False  
362       80    100           3     False  
363       50     25           3     False

In [28]:

df[~df['Name'].str.contains('Mega')].head()
# ~ means "NOT" 

Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
#                                                                            
1   Bulbasaur  Grass  Poison  45      49       49       65       65     45   
2     Ivysaur  Grass  Poison  60      62       63       80       80     60   
3    Venusaur  Grass  Poison  80      82       83      100      100     80   
4  Charmander   Fire     NaN  39      52       43       60       50     65   
5  Charmeleon   Fire     NaN  58      64       58       80       65     80   

   Generation Legendary  
#                        
1           1     False  
2           1     False  
3           1     False  
4           1     False  
5           1     False

In [32]:
df[df['Name'].str.contains('^Pi')].head()
# symbol ('^') means starts_with

Name    Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
#                                                                         
16               Pidgey    Normal  Flying  40      45       40       35   
17            Pidgeotto    Normal  Flying  63      60       55       50   
18              Pidgeot    Normal  Flying  83      80       75       70   
18  PidgeotMega Pidgeot    Normal  Flying  83      80       80      135   
25              Pikachu  Electric     NaN  35      55       40       50   

    Sp. Def  Speed  Generation Legendary  
#                                         
16       35     56           1     False  
17       50     71           1     False  
18       70    101           1     False  
18       80    121           1     False  
25       50     90           1     False

In [33]:
import re #regular expressions

df.loc[df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)].head()

Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
#                                                                       
1              Bulbasaur  Grass  Poison  45      49       49       65   
2                Ivysaur  Grass  Poison  60      62       63       80   
3               Venusaur  Grass  Poison  80      82       83      100   
3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation Legendary  
#                                        
1       65     45           1     False  
2       80     60           1     False  
3      100     80           1     False  
3      120     80           1     False  
4       50     65           1     False

In [39]:
# isin

df[df['Type 2'].isin(['Poison', 'Flying'])].head()

Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
#                                                                       
1              Bulbasaur  Grass  Poison  45      49       49       65   
2                Ivysaur  Grass  Poison  60      62       63       80   
3               Venusaur  Grass  Poison  80      82       83      100   
3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
6              Charizard   Fire  Flying  78      84       78      109   

   Sp. Def  Speed  Generation Legendary  
#                                        
1       65     45           1     False  
2       80     60           1     False  
3      100     80           1     False  
3      120     80           1     False  
6       85    100           1     False

### Reset_index(inplace=True)

inplace=True so that it will be droped permanently

In [ ]:
filtered.reset_index(drop=True, inplace=True)
filtered.head()

### Save document to CSV

In [ ]:
filtered.to_csv('data/filtered.csv')

### Missind Data
1. dropna()
2. fillna()
3. isnull()

In [56]:
# DROPNA

# dropna(how="any"/"all"), it is "any" by default, meaning it will drop any row that has Nan value, 
# "all": will only drop a row if all the row value has Nan Value
df.dropna(how="any")
# OR
df.dropna()

# FILLNA

df.fillna(value=20)

# ISNA
df.isnull()

# NOTNULL
df.notnull().head()

Name Type 1 Type 2    HP Attack Defense Sp. Atk Sp. Def Speed Generation  \
#                                                                             
1  True   True   True  True   True    True    True    True  True       True   
2  True   True   True  True   True    True    True    True  True       True   
3  True   True   True  True   True    True    True    True  True       True   
3  True   True   True  True   True    True    True    True  True       True   
4  True   True  False  True   True    True    True    True  True       True   

  Legendary  
#            
1      True  
2      True  
3      True  
3      True  
4      True